### ISSUE TITLE
Try on closed

### ISSUE THREAD

**Issue by arihSiqueira** [arihSiqueira/RoupahApp#1]
Testando aqui o esquema de issue. 

Seguinte, ficou definido:
- @pliniopereira : Layout.
  -Arihane, @biammsilva : Funcionalidade.

Ps: Vlw a dica Plinio

**Comment by pliniopereira** [comment]
@arihSiqueira ciente

**Comment by pliniopereira** [comment]
Para marcar a pessoa use o @, que já vai aparecer a pessoa para marcar.
